# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.13-slim

WORKDIR /app

# Copy the project files into the container
COPY . .

# Install pip and project dependencies (using hatchling through pip)
RUN pip install --no-cache-dir .

# Expose any necessary port if applicable (MCP over stdio, so likely not needed)

# Run the MCP server via its entrypoint command provided in pyproject.toml
CMD ["mcp-aiven"]
